apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
       app: my-db
  template:
    metadata:
      labels:
        app: my-db
    spec:
      containers:
      - name: mongodb-app
        image: mongo
        ports:
          - containerPort: 27017
            name: mongo-port